# Generated by Django 4.1.7 on 2023-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=255, null=True)),
                ('predicat', models.CharField(choices=[('None', 'All'), ('SourceIP', 'Source IP'), ('DestinationIP', 'Destination IP'), ('SourcePort', 'SourcePort'), ('DestinationPort', 'Destination Port'), ('TimeStamp', 'Time Stamp'), ('Duration', 'Duration'), ('FlowBytesSent', 'Flow Bytes Sent'), ('FlowSentRate', 'Flow Sent Rate'), ('FlowBytesReceived', 'Flow Bytes Received'), ('FlowReceivedRate', 'Flow Received Rate'), ('PacketLengthVariance', 'Packet Length Variance'), ('PacketLengthStandardDeviation', 'Packet Length Standard Deviation'), ('PacketLengthMean', 'Packet Length Mean'), ('PacketLengthMedian', 'Packet Length Median'), ('PacketLengthMode', 'Packet Length Mode'), ('PacketLengthSkewFromMedian', 'Packet Length Skew From Median'), ('PacketLengthSkewFromMode', 'Packet Length Skew From Mode'), ('PacketLengthCoefficientofVariation', 'Packet Length Coefficient of Variation'), ('PacketTimeVariance', 'Packet Time Variance'), ('PacketTimeStandardDeviation', 'Packet Time Standard Deviation'), ('PacketTimeMean', 'Packet TimeMean'), ('PacketTimeMedian', 'Packet Time Median'), ('PacketTimeMode', 'Packet Time Mode'), ('PacketTimeSkewFromMedian', 'Packet Time Skew From Median'), ('PacketTimeSkewFromMode', 'Packet Time Skew From Mode'), ('PacketTimeCoefficientofVariation', 'Packet Time Coefficient of Variation'), ('ResponseTimeTimeVariance', 'Response Time Time Variance'), ('ResponseTimeTimeStandardDeviation', 'Response Time Time Standard Deviation'), ('ResponseTimeTimeMean', 'Response Time Time Mean'), ('ResponseTimeTimeMedian', 'Response Time TimeMedian'), ('ResponseTimeTimeMode', 'Response Time Time Mode'), ('ResponseTimeTimeSkewFromMedian', 'Response Time Time Skew From Median'), ('ResponseTimeTimeSkewFromMode', 'Response Time Time Skew From Mode'), ('ResponseTimeTimeCoefficientofVariation', 'Response Time Time Coefficient of Variation'), ('DoH', 'DoH')], default=None, max_length=255, null=True)),
                ('objectV', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
