# Generated by Django 4.1.7 on 2023-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rdf_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparql_query', models.TextField(max_length=1000)),
            ],
        ),
    ]
