# Generated by Django 4.1.7 on 2023-03-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triples', '0002_rdf_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Triple',
            new_name='DoHTriple',
        ),
        migrations.DeleteModel(
            name='rdf_query',
        ),
    ]
